#!/bin/sh
. "$(dirname "${0}")/_/husky.sh"

# Read all the pushes being done.
SUCCESS="true"
while read LOCAL_REF LOCAL_SHA REMOTE_REF REMOTE_SHA; do
    # Ignore pushes not targeting main.
    if [ "${REMOTE_REF}" != "refs/heads/main" ]; then
        continue
    fi

    # Read all the commits to be pushed.
    COMMITS_TO_PUSH=$(
        git log "${REMOTE_SHA}..${LOCAL_SHA}" --pretty=format:"%H" --reverse |
        cut -f 1
    )

    # For each commit, lint it.
    if ! echo -n "${COMMITS_TO_PUSH}" |
        xargs -L 1 -I {} bash -c "
            # Use script to capture colorized and styled output to a variable.
            OUTPUT=\$(
                script /dev/null --quiet --return --command \\
                    \"COMMIT=\"{}\" npm run -s -- lint-commit\"
            )

            # Print lint output with the commit hash it was linting.
            if [ \"\${?}\" != \"0\" ]; then
                echo \"Linting commit {} failed:\"
                echo \"\${OUTPUT}\"
                exit 1
            fi
        "
    then
        SUCCESS="false"
    fi
done

# If any commit fails to lint, abort the push.
if [ "${SUCCESS}" != "true" ]; then
    exit 1
fi
