# Runs the linter on a pull request.

name: Lint PR

on:
- pull_request

jobs:
  lint:
    # Includes `bazelisk`.
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#:~:text=Bazel%204.2.1-,Bazelisk,-1.10.1
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: bazel run @nodejs//:npm -- ci

    # Lint each commit in the given PR.
    - name: Lint PR
      run: |
        # Get all commits in PR.
        readonly PR_COMMITS=$(
          git log "${{ github.base_ref }}..${{ github.head_ref }}" --pretty=format:"%H" --reverse |
          cut -f 1
        )
        
        # Lint each commit.
        if ! echo -n "${PR_COMMITS}" |
          xargs -d " " -L 1 -I {} bash -c "COMMIT=\"{}\" bazel run @nodejs//:npm -- run -s -- lint-commit"
        then
          # One commit failed to lint, fail the GitHub action.
          exit 1
        fi
