# This workflow will do a clean install of Node dependencies, executes all tests
# and then publishes the package to NPM with the given semver. Should be
# executed manually via the GitHub actions UI.

name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: NPM semver to release as.
        required: true
        default: "0.0.0-PLACEHOLDER"
      prerelease:
        description: |
          Whether or not to mark the GitHub release as a prerelease. Possible
          values: "true", "false".
        default: "false"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

    # Checkout the repository.
    - uses: actions/checkout@v2

    # Install NodeJS.
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: 'https://registry.npmjs.org'

    # Install the package, including Bazel.
    - name: Install
      run: npm ci

    # Build and test the entire repository.
    - name: Test
      run: npm test
    
    # Publish the package.
    - name: Publish
      run: npm run release
      env:
        BAZEL_RULES_PRERENDER_VERSION: ${{ github.event.inputs.version }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
    
    # Tag the commit and create a release on GitHub.
    - name: Tag and Create Draft Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: releases/${{ github.event.inputs.version }}
        release_name: ${{ github.event.inputs.version }}
        prerelease: ${{ github.event.inputs.prerelease == 'true' }}
        body: https://www.npmjs.com/package/rules_prerender/v/${{ github.event.inputs.version }}
        draft: true

    # Notify the user that the release is completed.
    - name: Complete
      run: |
        echo "Draft release created at ${RELEASE_URL}."
        echo "Please update the changelog and publish the release."
      env:
        RELEASE_URL: https://github.com/dgp1130/rules_prerender/releases/tag/releases%2F{{ github.event.inputs.version }}
