# This workflow will do a clean install of Node dependencies, executes all tests
# and then publishes the package to NPM with the given semver. Should be
# executed manually via the GitHub actions UI.

name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: NPM semver to release as.
        required: true
        default: "0.0.0-PLACEHOLDER"
      prerelease:
        description: |
          Whether or not to mark the GitHub release as a prerelease. Possible
          values: "true", "false".
        required: false
        default: "false"

jobs:
  publish:
    # Includes `bazelisk`.
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#:~:text=Bazel%204.2.1-,Bazelisk,-1.10.1
    runs-on: ubuntu-20.04

    steps:

    # Checkout the repository.
    - uses: actions/checkout@v3

    - name: Cache Bazel
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
        restore-keys: |
          ${{ runner.os }}-bazel-

    - name: Get pnpm store directory
      id: pnpm-cache-dir
      run: |
        echo "PNPM_STORE_PATH=$(bazel run @pnpm --config ci -- store path --silent)" >> "${GITHUB_OUTPUT}"

    - name: Cache pnpm
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache-dir.outputs.PNPM_STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install
      run: bazel run @pnpm --config ci -- install --dir $PWD --frozen-lockfile

    # Build and test the entire repository.
    - name: Test
      run: |
        # Run `bazel test //...` over all workspaces in the repository.
        find . -name WORKSPACE.bazel -printf "%h\n" |
        sort |
        xargs -I {} bash -c "(cd {} && bazel test //... --config ci)"

    - name: Tar Workspace
      run: |
        # Use the same prefix as what GitHub generates for source archives.
        readonly VERSION="${{ github.event.inputs.version }}"
        readonly PREFIX="rules_prerender-${VERSION}"
        readonly ARCHIVE="rules_prerender-bazel_workspace-${VERSION}.tar.gz"

        git archive --format=tar --prefix="${PREFIX}/" "HEAD" | gzip > "${ARCHIVE}"
        readonly SHA=$(shasum -a 256 "${ARCHIVE}" | awk '{ print $1 }')

        cat tools/publish/install_instructions.md |
          sed "s,\$VERSION,${VERSION},g" |
          sed "s,\$PREFIX,${PREFIX},g" |
          sed "s,\$ARCHIVE,${ARCHIVE},g" |
          sed "s,\$SHA,${SHA},g" \
          > release_notes.txt

    # Publish the package. Use the CI configuration to reuse the existing cache
    # and have a more polished output.
    - name: Publish
      run: |
        # Append NPM token to `.npmrc` file.
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" >> .npmrc

        # Build all the packages to make sure they are buildable and the labels haven't
        # changed. This helps prevent publishing one package and then failing to build
        # the next one.
        bazel build --config ci --config release \
          //:rules_prerender_pkg_publish \
          //packages/declarative_shadow_dom:pkg_publish \
          //packages/preact:pkg_publish

        # Tar the NPM packages prior to publish to make sure the file paths are correct.
        tar -czf rules_prerender-${{ github.event.inputs.version }}.tar.gz \
            dist/bin/rules_prerender_pkg/
        tar -czf rules_prerender-declarative_shadow_dom-${{ github.event.inputs.version }}.tar.gz \
            dist/bin/packages/declarative_shadow_dom/pkg/
        tar -czf rules_prerender-preact-${{ github.event.inputs.version }}.tar.gz \
            dist/bin/packages/preact/pkg/

        # Publish the packages.
        bazel run --config ci --config release //:rules_prerender_pkg_publish
        bazel run --config ci --config release //packages/declarative_shadow_dom:pkg_publish
        bazel run --config ci --config release //packages/preact:pkg_publish

        # Remove the token from the `.npmrc` file, it should no longer be needed.
        sed -i "/${{ secrets.NPM_ACCESS_TOKEN }}/d" .npmrc
      env:
        BAZEL_RULES_PRERENDER_VERSION: ${{ github.event.inputs.version }}

    # Tag the commit and create a release on GitHub.
    - name: Tag and Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body_path: release_notes.txt
        tag_name: releases/${{ github.event.inputs.version }}
        release_name: ${{ github.event.inputs.version }}
        prerelease: ${{ github.event.inputs.prerelease == 'true' }}
        draft: true

    # Upload `@rules_prerender` workspace to the GitHub release.
    - name: Upload `rules_prerender` to GitHub
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: rules_prerender-bazel_workspace-${{ github.event.inputs.version }}.tar.gz
        asset_name: rules_prerender-bazel_workspace-${{ github.event.inputs.version }}.tar.gz
        asset_content_type: application/gzip

    # Upload `rules_prerender` NPM package to the GitHub release.
    - name: Upload `rules_prerender` to GitHub
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: rules_prerender-${{ github.event.inputs.version }}.tar.gz
        asset_name: rules_prerender-${{ github.event.inputs.version }}.tar.gz
        asset_content_type: application/gzip

    # Upload `@rules_prerender/declarative_shadow_dom` to the GitHub release.
    - name: Upload `@rules_prerender/declarative_shadow_dom` to GitHub
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: rules_prerender-declarative_shadow_dom-${{ github.event.inputs.version }}.tar.gz
        asset_name: rules_prerender-declarative_shadow_dom-${{ github.event.inputs.version }}.tar.gz
        asset_content_type: application/gzip

    # Upload `@rules_prerender/preact` to the GitHub release.
    - name: Upload `@rules_prerender/preact` to GitHub
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: rules_prerender-preact-${{ github.event.inputs.version }}.tar.gz
        asset_name: rules_prerender-preact-${{ github.event.inputs.version }}.tar.gz
        asset_content_type: application/gzip

    # Notify the user that the release is completed.
    - name: Complete
      run: |
        echo "Draft release created at ${RELEASE_URL}."
        echo "Please update the changelog and publish the release."
      env:
        RELEASE_URL: https://github.com/dgp1130/rules_prerender/releases/tag/releases%2F${{ github.event.inputs.version }}
